"""Initial schema: users, resumes, interviews, turns, scores, reports.

Revision ID: e2d98c7b8acf
Revises:
Create Date: 2026-09-21 13:04:35.571894
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e2d98c7b8acf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "resumes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resumes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_table(
        "interviews",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=160), nullable=False),
        sa.Column(
            "seniority",
            sa.Enum("intern", "junior", "mid", "senior", "staff", name="seniority"),
            nullable=False,
        ),
        sa.Column(
            "persona",
            sa.Enum("friendly", "neutral", "skeptical", "time_pressed", name="persona"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("created", "in_progress", "completed", "abandoned", name="interview_status"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_questions", sa.Integer(), nullable=False),
        sa.Column("llm_provider", sa.String(length=32), nullable=False),
        sa.Column("llm_model", sa.String(length=120), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_interviews_resume_id_resumes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_interviews_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_interviews_thread_id")),
    )
    op.create_index(op.f("ix_interviews_status"), "interviews", ["status"], unique=False)
    op.create_index(op.f("ix_interviews_user_id"), "interviews", ["user_id"], unique=False)
    op.create_index("ix_interviews_user_status", "interviews", ["user_id", "status"], unique=False)
    op.create_table(
        "interview_reports",
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("competency_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delivery_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("improvements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_focus", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_interview_reports_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_reports")),
    )
    op.create_index(
        op.f("ix_interview_reports_interview_id"),
        "interview_reports",
        ["interview_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_interview_reports_overall_score"),
        "interview_reports",
        ["overall_score"],
        unique=False,
    )
    op.create_table(
        "turns",
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("opening", "main", "follow_up", "closing", name="turn_kind"),
            nullable=False,
        ),
        sa.Column(
            "competency",
            sa.Enum(
                "communication",
                "technical_depth",
                "problem_solving",
                "ownership",
                "collaboration",
                "culture_fit",
                name="competency",
            ),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("audio_duration_s", sa.Float(), nullable=True),
        sa.Column("transcription_confidence", sa.Float(), nullable=True),
        sa.Column("word_timings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_turns_interview_id_interviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("interview_id", "index", name="uq_turns_interview_id_index"),
    )
    op.create_index(op.f("ix_turns_interview_id"), "turns", ["interview_id"], unique=False)
    op.create_table(
        "turn_scores",
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("model_score", sa.Float(), nullable=False),
        sa.Column("llm_score", sa.Float(), nullable=True),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.Column("blended_score", sa.Float(), nullable=False),
        sa.Column("structure", sa.Float(), nullable=True),
        sa.Column("specificity", sa.Float(), nullable=True),
        sa.Column("clarity", sa.Float(), nullable=True),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rubric_notes", sa.Text(), nullable=True),
        sa.Column("scorer_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["turns.id"], name=op.f("fk_turn_scores_turn_id_turns"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turn_scores")),
    )
    op.create_index(
        op.f("ix_turn_scores_blended_score"), "turn_scores", ["blended_score"], unique=False
    )
    op.create_index(op.f("ix_turn_scores_turn_id"), "turn_scores", ["turn_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turn_scores_turn_id"), table_name="turn_scores")
    op.drop_index(op.f("ix_turn_scores_blended_score"), table_name="turn_scores")
    op.drop_table("turn_scores")
    op.drop_index(op.f("ix_turns_interview_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index(op.f("ix_interview_reports_overall_score"), table_name="interview_reports")
    op.drop_index(op.f("ix_interview_reports_interview_id"), table_name="interview_reports")
    op.drop_table("interview_reports")
    op.drop_index("ix_interviews_user_status", table_name="interviews")
    op.drop_index(op.f("ix_interviews_user_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_status"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # PostgreSQL enum types outlive their tables; Alembic does not drop them.
    for enum_name in ("turn_kind", "competency", "interview_status", "persona", "seniority"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
